name: Release prebuilt binary

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: yarn install

      - name: Install pkg
        run: yarn add pkg

      - name: Build binary
        run: yarn pkg .

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "cf-warp-*"
